Update to resolve install issues
Added WORKDIR to line 34 to resolve the following errors:
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not in a git directory

Added lines 60 and 61 to resolve the following errors:
ERROR [mispevent.py:52 - <module>() ] Cannot import jsonschema
Traceback (most recent call last):
  File "/var/www/MISP/PyMISP/pymisp/mispevent.py", line 50, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
WARNING [__init__.py:46 - <module>() ] Unable to load pymisp properly: No module named 'requests'

Edited line 136 to resolve the following error:
/bin/sh: 1: cannot create /etc/php/7.0/mods-available/ssdeep.ini: Directory nonexistent
WARNING: Module ssdeep ini file doesn't exist under /etc/php/7.2/mods-available
WARNING: Module ssdeep ini file doesn't exist under /etc/php/7.2/mods-available